name: "Docker"

on:
  push:
    paths:
      - "migration/**"
      - "src/**"
      - ".dockerignore"
      - "build.rs"
      - "Cargo.lock"
      - "Cargo.toml"
      - "Dockerfile"
    branches:
      - "trunk"
  workflow_dispatch:

jobs:
  docker:
    permissions:
      contents: "read"
      packages: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130" # v3

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f" # v3

      - name: "Login to Docker Hub"
        uses: "docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef" # v3
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Extract metadata for Docker"
        id: "meta"
        uses: "docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051" # v5
        with:
          images: "ghcr.io/Phat1509/shoes-store-backend"

      - name: "Build and push"
        uses: "docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83" # v6
        with:
          context: "{{defaultContext}}:backend"
          push: "${{ github.event_name != 'pull_request' }}"
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"
          file: "Dockerfile"
